/*
 * Stoatworks Labs - About window data for Relay.
 *
 * PROVISIONAL hand copy, adapted from wipe's generated header (2026-09-24).
 * The real one is GENERATED by stoatworks-backend/scripts/sync-about.py from
 * the website's projects.json when the plugin is registered in the fleet;
 * that sync overwrites this file. `guide` is empty because no user guide
 * exists yet, so the About block has no User guide button.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Relay";
    inline constexpr auto slug = "relay";
    inline constexpr auto hook = "An A/B cut made by a relay, bounce and all, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/relay/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/relay";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
